/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.97
 * Generated at: 2025-01-12 14:19:16 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.join.view.login;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import com.kh.dev.join.model.UsersVO;

public final class mypage_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(1);
    _jspx_dependants.put("/join/headerNav.jsp", Long.valueOf(1736691260422L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.LinkedHashSet<>(2);
    _jspx_imports_classes.add("com.kh.dev.join.model.UsersVO");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");

	request.setCharacterEncoding("UTF-8");
    // 세션에서 사용자 정보 가져오기
    UsersVO user = (UsersVO) session.getAttribute("user");
    if (user == null) {
        response.sendRedirect("login.jsp"); // 로그인하지 않은 상태에서 접근 시 로그인 페이지로 리다이렉트
        return;
    }

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"ko\">\r\n");
      out.write("<head>\r\n");
      out.write("    <meta charset=\"UTF-8\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"mypage.css\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"../../headerNav.css\">\r\n");
      out.write("    <title>마이페이지</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("	<header>\r\n");
      out.write("        <div class=\"logo_set\">\r\n");
      out.write("            <a href=\"../../main.jsp\"><i class=\"fa-brands fa-stack-overflow\"></i><span style=\"line-height: 90px; padding-left: 20px;\">stack overflow</span></a>\r\n");
      out.write("        </div>\r\n");
      out.write("        <ul class=\"dropdown_list\">\r\n");
      out.write("            <li><a href=\"/join/join/view/join/register.jsp\" class=\"dropbtn\">회원가입</a>\r\n");
      out.write("                <div class=\"dropdown-content\">\r\n");
      out.write("                    <a href=\"/join/join/view/login/login.jsp\">로그인</a>\r\n");
      out.write("                    <a href=\"/join/join/view/login/mypage.jsp\">마이페이지</a>\r\n");
      out.write("                </div></li>\r\n");
      out.write("            <li><a href=\"/join/join/view/board/writeForm.jsp\" class=\"dropbtn\">게시판</a>\r\n");
      out.write("                <div class=\"dropdown-content\">\r\n");
      out.write("                    <a href=\"/join/join/view/notice/list.jsp\">공지사항</a>\r\n");
      out.write("                    <a href=\"/join/join/view/fileupload/fileuploadList.jsp\">자료실</a>\r\n");
      out.write("                </div></li>\r\n");
      out.write("            <li><a href=\"#\" class=\"dropbtn\">서비스 안내</a>\r\n");
      out.write("                <div class=\"dropdown-content\">\r\n");
      out.write("                    <a href=\"#\">menu1</a>\r\n");
      out.write("                    <a href=\"#\">menu2</a>\r\n");
      out.write("                    <a href=\"#\">menu3</a>\r\n");
      out.write("                </div></li>\r\n");
      out.write("            <li><a href=\"#\" class=\"dropbtn\">menu</a>\r\n");
      out.write("                <div class=\"dropdown-content\">\r\n");
      out.write("                    <a href=\"#\">menu1</a>\r\n");
      out.write("                    <a href=\"#\">menu2</a>\r\n");
      out.write("                    <a href=\"#\">menu3</a>\r\n");
      out.write("                </div></li>\r\n");
      out.write("        </ul>\r\n");
      out.write("        <div class=\"icon_set\">\r\n");
      out.write("            <a href=\"#\"><i class=\"fa-brands fa-facebook\"></i></a>\r\n");
      out.write("            <a href=\"#\"><i class=\"fa-brands fa-instagram\"></i></a>\r\n");
      out.write("        </div>\r\n");
      out.write("    </header>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
      out.write("\r\n");
      out.write("    <div class=\"main_wrap\">\r\n");
      out.write("        <form id=\"mypageForm\" action=\"mypageProc.jsp\" method=\"post\">\r\n");
      out.write("            <h2>마이페이지</h2>\r\n");
      out.write("\r\n");
      out.write("            <label for=\"id\">아이디 (수정 불가)</label>\r\n");
      out.write("            <input type=\"text\" id=\"id\" name=\"id\" value=\"");
      out.print( user.getId() );
      out.write("\" readonly>\r\n");
      out.write("\r\n");
      out.write("            <label for=\"name\">이름</label>\r\n");
      out.write("            <input type=\"text\" id=\"name\" name=\"name\" value=\"");
      out.print( user.getName() );
      out.write("\" required>\r\n");
      out.write("\r\n");
      out.write("            <label for=\"email\">이메일</label>\r\n");
      out.write("            <input type=\"email\" id=\"email\" name=\"email\" value=\"");
      out.print( user.getEmail() );
      out.write("\" required>\r\n");
      out.write("\r\n");
      out.write("            <label for=\"phone\">전화번호</label>\r\n");
      out.write("            <input type=\"text\" id=\"phone1\" name=\"phone1\" value=\"");
      out.print( user.getPhone1() );
      out.write("\" required>\r\n");
      out.write("            <input type=\"text\" id=\"phone2\" name=\"phone2\" value=\"");
      out.print( user.getPhone2() );
      out.write("\" required>\r\n");
      out.write("            <input type=\"text\" id=\"phone3\" name=\"phone3\" value=\"");
      out.print( user.getPhone3() );
      out.write("\" required>\r\n");
      out.write("\r\n");
      out.write("            <label for=\"gender\">성별</label>\r\n");
      out.write("            <select id=\"gender\" name=\"gender\" required>\r\n");
      out.write("                <option value=\"male\" ");
      out.print( "male".equals(user.getGender()) ? "selected" : "" );
      out.write(">남성</option>\r\n");
      out.write("                <option value=\"female\" ");
      out.print( "female".equals(user.getGender()) ? "selected" : "" );
      out.write(">여성</option>\r\n");
      out.write("            </select>\r\n");
      out.write("\r\n");
      out.write("             <!-- 정보 수정 버튼 -->\r\n");
      out.write("            <button type=\"submit\">정보수정</button>\r\n");
      out.write("\r\n");
      out.write("            <!-- 로그아웃 버튼 -->\r\n");
      out.write("            <button type=\"button\" onclick=\"location.href='logout.jsp'\" class=\"logout-button\">로그아웃</button>\r\n");
      out.write("    </div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
