/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.97
 * Generated at: 2024-12-22 06:42:14 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.join;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class register_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(1);
    _jspx_dependants.put("/join/headerNav.jsp", Long.valueOf(1734775280416L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\r');
      out.write('\n');

    // 전달된 인증번호를 받음
    String verifiedCode = (String) session.getAttribute("verifiedCode");

      out.write("\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("<head>\r\n");
      out.write("    <meta charset=\"UTF-8\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("    <title>Document</title>\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"register.css\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"headerNav.css\">\r\n");
      out.write("    <script src=\"register.js\"></script>\r\n");
      out.write("    <script src=\"https://kit.fontawesome.com/70bcde4f7a.js\" crossorigin=\"anonymous\"></script>\r\n");
      out.write("</head>\r\n");
      out.write("<body onload=\"onLoad();\" >\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("	<header>\r\n");
      out.write("        <div class=\"logo_set\">\r\n");
      out.write("            <a href=\"#\"><i class=\"fa-brands fa-stack-overflow\"></i><span style=\"line-height: 90px; padding-left: 20px;\">stack overflow</span></a>\r\n");
      out.write("        </div>\r\n");
      out.write("        <ul class=\"dropdown_list\">\r\n");
      out.write("            <li><a href=\"/join/join/register.jsp\" class=\"dropbtn\">회원가입</a>\r\n");
      out.write("                <div class=\"dropdown-content\">\r\n");
      out.write("                    <a href=\"#\">menu1</a>\r\n");
      out.write("                    <a href=\"#\">menu2</a>\r\n");
      out.write("                    <a href=\"#\">menu3</a>\r\n");
      out.write("                </div></li>\r\n");
      out.write("            <li><a href=\"/join/join/view/writeForm.jsp\" class=\"dropbtn\">게시판</a>\r\n");
      out.write("                <div class=\"dropdown-content\">\r\n");
      out.write("                    <a href=\"#\">menu1</a>\r\n");
      out.write("                    <a href=\"#\">menu2</a>\r\n");
      out.write("                    <a href=\"#\">menu3</a>\r\n");
      out.write("                </div></li>\r\n");
      out.write("            <li><a href=\"#\" class=\"dropbtn\">menu</a>\r\n");
      out.write("                <div class=\"dropdown-content\">\r\n");
      out.write("                    <a href=\"#\">menu1</a>\r\n");
      out.write("                    <a href=\"#\">menu2</a>\r\n");
      out.write("                    <a href=\"#\">menu3</a>\r\n");
      out.write("                </div></li>\r\n");
      out.write("            <li><a href=\"#\" class=\"dropbtn\">menu</a>\r\n");
      out.write("                <div class=\"dropdown-content\">\r\n");
      out.write("                    <a href=\"#\">menu1</a>\r\n");
      out.write("                    <a href=\"#\">menu2</a>\r\n");
      out.write("                    <a href=\"#\">menu3</a>\r\n");
      out.write("                </div></li>\r\n");
      out.write("        </ul>\r\n");
      out.write("        <div class=\"icon_set\">\r\n");
      out.write("            <a href=\"#\"><i class=\"fa-brands fa-facebook\"></i></a>\r\n");
      out.write("            <a href=\"#\"><i class=\"fa-brands fa-instagram\"></i></a>\r\n");
      out.write("        </div>\r\n");
      out.write("    </header>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
      out.write("\r\n");
      out.write("    <main>\r\n");
      out.write("        <div class=\"main_wrap\">\r\n");
      out.write("            <div class=\"title_main\"><div>stack overflow</div>\r\n");
      out.write("                <form action=\"registerProc.jsp\" method=\"post\" id=\"myform\" name=\"regForm\">\r\n");
      out.write("                    <label for=\"id\">&nbsp;&nbsp;아이디</label><br>\r\n");
      out.write("                    <input type=\"text\" name=\"id\" id=\"id\"><span></span><br>\r\n");
      out.write("                    <label for=\"pwd\">&nbsp;&nbsp;비밀번호</label><br>\r\n");
      out.write("                    <input type=\"password\" name=\"pwd\" id=\"pwd\"><span></span><br>\r\n");
      out.write("                    <label for=\"pwdconfirm\">&nbsp;&nbsp;비밀번호 재확인</label><br>\r\n");
      out.write("                    <input type=\"password\" name=\"pwdconfirm\" id=\"pwdconfirm\"><span>&nbsp;&nbsp;</span><br>\r\n");
      out.write("                    <label for=\"name\">&nbsp;&nbsp;이름</label><br>\r\n");
      out.write("                    <input type=\"text\" name=\"name\" id=\"name\"><span></span><br>\r\n");
      out.write("                    <label for=\"birthday\">&nbsp;&nbsp;생년월일</label><br>\r\n");
      out.write("                    <input type=\"text\" name=\"year\" id=\"year\" placeholder=\"년(4자)\"><span></span>\r\n");
      out.write("                    <select name=\"month\" id=\"month\">\r\n");
      out.write("                        <option value=\"월\">월</option>\r\n");
      out.write("                        <option value=\"1\">1</option>\r\n");
      out.write("                        <option value=\"2\">2</option>\r\n");
      out.write("                        <option value=\"3\">3</option>\r\n");
      out.write("                        <option value=\"4\">4</option>\r\n");
      out.write("                        <option value=\"5\">5</option>\r\n");
      out.write("                        <option value=\"6\">6</option>\r\n");
      out.write("                        <option value=\"7\">7</option>\r\n");
      out.write("                        <option value=\"8\">8</option>\r\n");
      out.write("                        <option value=\"9\">9</option>\r\n");
      out.write("                        <option value=\"10\">10</option>\r\n");
      out.write("                        <option value=\"11\">11</option>\r\n");
      out.write("                        <option value=\"12\">12</option>\r\n");
      out.write("                    </select>\r\n");
      out.write("                    <input type=\"text\" name=\"day\" id=\"day\" placeholder=\"일\"><span></span><br>\r\n");
      out.write("                    <label for=\"gender\">&nbsp;&nbsp;성별</label><br>\r\n");
      out.write("                    <select name=\"gender\" id=\"gender\">\r\n");
      out.write("                        <option value=\"성별\">성별</option>\r\n");
      out.write("                        <option value=\"남자\">남자</option>\r\n");
      out.write("                        <option value=\"여자\">여자</option>\r\n");
      out.write("                    </select><br>\r\n");
      out.write("                    <label for=\"email\">&nbsp;&nbsp;본인 확인 이메일</label><br>\r\n");
      out.write("                    <input type=\"email\" name=\"email\" id=\"email\" placeholder=\"필수입력\"><span></span><br>\r\n");
      out.write("                    <label for=\"phone\">&nbsp;&nbsp;휴대전화</label><br>\r\n");
      out.write("                    <select name=\"phone1\" id=\"phone1\">\r\n");
      out.write("                        <option value=\"대한민국\">대한민국 +82</option>\r\n");
      out.write("                        <option value=\"일본\">일본 +81</option>\r\n");
      out.write("                        <option value=\"베트남\">베트남 +84</option>\r\n");
      out.write("                        <option value=\"중국\">중국 +86</option>\r\n");
      out.write("                        <option value=\"영국\">영국 +44</option>\r\n");
      out.write("                        <option value=\"오스트레일리아\">오스트레일리아 +61</option>\r\n");
      out.write("                        <option value=\"필리핀\">필리핀 +63</option>\r\n");
      out.write("                        <option value=\"태국\">태국 +66</option>\r\n");
      out.write("                        <option value=\"미국\">미국 +1</option>\r\n");
      out.write("                        <option value=\"페루\">페루 +51</option>\r\n");
      out.write("                        <option value=\"멕시코\">멕시코 +52</option>\r\n");
      out.write("                        <option value=\"브라질\">브라질 +55</option>\r\n");
      out.write("                        <option value=\"칠레\">칠레 +56</option>\r\n");
      out.write("                    </select><br>\r\n");
      out.write("                    <input type=\"text\" name=\"phone2\" id=\"phone2\" placeholder=\"전화번호 입력\"><span></span><button type=\"button\" id=\"confirmnumber\" onclick=\"confirmNumber()\">인증번호 받기</button><br>\r\n");
      out.write("                    <input type=\"text\" name=\"phone3\" id=\"phone3\" placeholder=\"인증번호를 입력하세요\" value=\"");
      out.print( verifiedCode != null ? verifiedCode : "" );
      out.write("\"><br>\r\n");
      out.write("                    <button type=\"submit\" id=\"join\" onclick=\"inputCheck()\">가입하기</button>\r\n");
      out.write("                </form>\r\n");
      out.write("            </div>\r\n");
      out.write("            \r\n");
      out.write("        </div>\r\n");
      out.write("        <nav>NAV</nav>\r\n");
      out.write("        <aside>ASIDE</aside>\r\n");
      out.write("    </main>\r\n");
      out.write("    <footer>FOOTER</footer>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
